name: Build Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.9.1
        with:
          cmake-version: '3.25.0'

      - name: Clone OBS Studio (SDK)
        run: |
          git clone --depth=1 https://github.com/obsproject/obs-studio.git obs-sdk

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -Dobs_DIR=$(pwd)/obs-sdk/build

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos_ui_plugin
          path: build/Release/macos_ui_plugin.dll
