name: Build Windows DLL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive  # <--- вот это важно!

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure project with CMake
        run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64

      - name: Build project
        run: cmake --build build --config Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dll-release
          path: build/Release/*.dll
