name: Build OBS Plugin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Visual Studio environment
      uses: microsoft/setup-msbuild@v1.1

    - name: Download OBS SDK
      run: |
        if not exist obs-sdk (
          git clone --depth 1 https://github.com/obsproject/obs-studio.git obs-sdk
        )

    - name: Configure CMake
      run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -Dobs_DIR=obs-sdk/build

    - name: Build Release
      run: cmake --build build --config Release

    - name: Upload built DLL
      uses: actions/upload-artifact@v3
      with:
        name: obs-plugin-dll
        path: build/Release/*.dll
