name: Build OBS Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download OBS SDK
      run: |
        curl -L -o obs-sdk.zip https://github.com/obsproject/obs-studio/releases/download/29.1.3/obs-sdk.zip
        7z x obs-sdk.zip -obs-sdk
        dir obs-sdk

    - name: Configure CMake
      run: |
        cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -DOBS_SDK_DIR=${{ github.workspace }}/obs-sdk

    - name: Build with MSBuild
      run: |
        cmake --build build --config Release

    - name: Upload plugin DLL
      uses: actions/upload-artifact@v4
      with:
        name: obs-plugin
        path: |
          build/Release/*.dll
