name: Build OBS Plugin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download OBS SDK
      run: |
        curl -L -o obs-sdk.zip https://cdn-fastly.obsproject.com/downloads/obs-sdk-29.1.3.zip

    - name: Extract OBS SDK
      run: |
        powershell -Command "Expand-Archive -LiteralPath obs-sdk.zip -DestinationPath obs-sdk"

    - name: Configure CMake
      run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -Dobs_DIR="${{ github.workspace }}\obs-sdk"

    - name: Build plugin
      run: cmake --build build --config Release

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v3
      with:
        name: obs-plugin-dll
        path: build\Release\*.dll
