name: Build Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: chrisjshull/setup-cmake@v2
        with:
          cmake-version: '3.25.0'

      - name: Clone OBS Studio repo (SDK)
        run: |
          git clone --depth=1 https://github.com/obsproject/obs-studio.git obs-sdk

      - name: Build OBS SDK
        run: |
          mkdir obs-sdk/build
          cd obs-sdk/build
          cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd)/install -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          cmake --install . --config Release

      - name: Configure plugin build
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -Dobs_DIR=$(pwd)/obs-sdk/build/install/lib/cmake/obs

      - name: Build plugin
        run: cmake --build build --config Release

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos_ui_plugin.dll
          path: build/Release/macos_ui_plugin.dll
